# Generated by Django 2.1.7 on 2019-04-09 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mondayStartTime', models.TimeField()),
                ('mondayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('mondayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('tuesdayStartTime', models.TimeField()),
                ('tuesdayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('tuesdayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('wednesdayStartTime', models.TimeField()),
                ('wednesdayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('wednesdayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('thursdayStartTime', models.TimeField()),
                ('thursdayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('thursdayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('fridayStartTime', models.TimeField()),
                ('fridayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('fridayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('saturdayStartTime', models.TimeField()),
                ('saturdayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('saturdayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('sundayStartTime', models.TimeField()),
                ('sundayShiftLengthHours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('sundayShiftLengthMinutes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StaffMember')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='startDate',
            field=models.DateField(unique=True),
        ),
    ]
